### ISSUE TITLE
Create static Permission class

### ISSUE THREAD

**Issue by holmjona** [edwardsjohnmartin/Phanon#6]
Create a class to hold all permissions as constants for consistency.

**Comment by valejose** [comment]
A Permissions enum class needs to be added so they can all be defined in one location and easily added/edited. A common method of adding enums in PHP is to a predefined class and making your enum class an extension of it. Two commonly used enum implementations are:
   [SplEnum](http://php.net/manual/en/class.splenum.php)
   [PHP-Enum](https://github.com/myclabs/php-enum)

**Comment by valejose** [comment]
Ended up going with PHP-Enum. Class is set up.
